language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
<<<<<<< HEAD
  - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
=======
  - docker-compose run app sh -c "python manage.py test && flake8"
>>>>>>> 9b14f69d7d247e74079e313f36de6e0363e7de00
