# Generated by Django 3.2.8 on 2021-11-04 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0003_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2018)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('Rent_date', models.DateField(default=datetime.datetime(2021, 11, 4, 22, 13, 33, 788765, tzinfo=utc))),
                ('Return_date', models.DateField(default=datetime.datetime(2021, 11, 4, 22, 13, 33, 788787, tzinfo=utc))),
                ('actors', models.ManyToManyField(to='moviestore.Actor')),
                ('categories', models.ManyToManyField(to='moviestore.Category')),
            ],
        ),
    ]
