# Generated by Django 3.2.8 on 2021-11-04 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0004_auto_20211104_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rent_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
