# Generated by Django 3.2.8 on 2021-11-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0005_auto_20211104_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
