# Generated by Django 3.2.8 on 2021-11-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0006_movie_user_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
