# Generated by Django 3.2.8 on 2021-11-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0007_alter_movie_user_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
